from lib.constants import *

RATINGS: list[int] = [
    S := 32,
    A := 16,
    B := 8,
    C := 4,
    D := 2,
    E := 1,
    _ := 0,
]


class ArmamentSpec:
    """
    Class representing an armament specification.
    """
    def __init__(self, name: str, type: str, affinities: list[str], STR: int, DEX: int, INT: int, FAI: int, ARC: int):
        self.name: str = name
        self.type: str = type
        self.affinities: list[str] = affinities
        self.STR: int = STR
        self.DEX: int = DEX
        self.INT: int = INT
        self.FAI: int = FAI
        self.ARC: int = ARC

    def get_best_stat(self) -> str:
        """
        Returns the name of the stat with the highest rating.
        """
        best_stat: int = max(self.STR, self.DEX, self.INT, self.FAI, self.ARC)
        res: list[str] = []
        if best_stat == self.STR:
            res.append("STR")
        if best_stat == self.DEX:
            res.append("DEX")
        if best_stat == self.INT:
            res.append("INT")
        if best_stat == self.FAI:
            res.append("FAI")
        if best_stat == self.ARC:
            res.append("ARC")
        return ", ".join(res)

    def get_stat_letter(self, stat_id: str) -> str:
        stat_value: int = getattr(self, stat_id)
        if stat_value == S:
            return "S"
        elif stat_value == A:
            return "A"
        elif stat_value == B:
            return "B"
        elif stat_value == C:
            return "C"
        elif stat_value == D:
            return "D"
        elif stat_value == E:
            return "E"
        else:
            return "-"

ARMAMENT_SPECS: set[ArmamentSpec] = set([
    ############ DAGGERS ############
    ArmamentSpec("Duchess' Dagger",              DAGGER,               [],                   E, S, _, _, _),
    ArmamentSpec("Dagger",                       DAGGER,               [],                   E, S, _, _, _),
    ArmamentSpec("Parrying Dagger",              DAGGER,               [],                   E, S, _, _, _),
    ArmamentSpec("Great Knife",                  DAGGER,               [BLEED],              E, S, _, _, _),
    ArmamentSpec("Miséricorde",                  DAGGER,               [],                   E, S, _, _, _),
    ArmamentSpec("Bloodstained Dagger",          DAGGER,               [BLEED],              E, S, _, _, _),
    ArmamentSpec("Erdsteel Dagger",              DAGGER,               [],                   E, A, _, D, _),
    ArmamentSpec("Wakizashi",                    DAGGER,               [],                   E, S, _, _, _),
    ArmamentSpec("Celebrant's Sickle",           DAGGER,               [],                   E, S, _, _, _),
    ArmamentSpec("Ivory Sickle",                 DAGGER,               [MAGIC],              E, A, D, _, _),
    ArmamentSpec("Crystal Knife",                DAGGER,               [MAGIC],              E, A, D, _, _),
    ArmamentSpec("Scorpion's Stinger",           DAGGER,               [SCARLET_ROT],        E, S, _, _, _),
    ArmamentSpec("Cinquedea",                    DAGGER,               [],                   E, S, _, _, _),
    ArmamentSpec("Glintstone Kris",              DAGGER,               [MAGIC],              E, A, D, _, _),
    ArmamentSpec("Reduvia",                      DAGGER,               [BLEED],              E, A, _, _, C),
    ArmamentSpec("Blade Of Calling",             DAGGER,               [HOLY],               E, A, _, D, _),
    ArmamentSpec("Black Knife",                  DAGGER,               [HOLY],               E, A, _, D, _),
    ############ STRAIGHT SWORDS ############
    ArmamentSpec("Short Sword",                  STRAIGHT_SWORD,       [],                   B, B, _, _, _),
    ArmamentSpec("Longsword",                    STRAIGHT_SWORD,       [],                   B, B, _, _, _),
    ArmamentSpec("Broadsword",                   STRAIGHT_SWORD,       [],                   B, B, _, _, _),
    ArmamentSpec("Weathered Straight Sword",     STRAIGHT_SWORD,       [],                   B, B, _, _, _),
    ArmamentSpec("Noble's Slender Sword",        STRAIGHT_SWORD,       [],                   B, B, _, _, _),
    ArmamentSpec("Lordsworn's Straight Sword",   STRAIGHT_SWORD,       [],                   B, B, _, _, _),
    ArmamentSpec("Cane Sword",                   STRAIGHT_SWORD,       [],                   B, B, _, _, _),
    ArmamentSpec("Warhawk's Talon",              STRAIGHT_SWORD,       [],                   B, B, _, _, _),
    ArmamentSpec("Lazuli Glintstone Sword",      STRAIGHT_SWORD,       [MAGIC],              C, C, C, _, _),
    ArmamentSpec("Carian Knight's Sword",        STRAIGHT_SWORD,       [MAGIC],              C, C, C, _, _),
    ArmamentSpec("Crystal Sword",                STRAIGHT_SWORD,       [MAGIC],              C, C, C, _, _),
    ArmamentSpec("Rotten Crystal Sword",         STRAIGHT_SWORD,       [MAGIC, SCARLET_ROT], C, C, C, _, _),
    ArmamentSpec("Miquellan Knight's Sword",     STRAIGHT_SWORD,       [HOLY],               C, C, _, C, _),
    ArmamentSpec("Ornamental Straight Sword",    STRAIGHT_SWORD,       [],                   B, B, _, _, _),
    ArmamentSpec("Golden Epitaph",               STRAIGHT_SWORD,       [HOLY],               C, C, _, C, _),
    ArmamentSpec("Sword Of St. Trina",           STRAIGHT_SWORD,       [MAGIC, SLEEP],       C, C, C, _, _),
    ArmamentSpec("Regalia Of Eochaid",           STRAIGHT_SWORD,       [MAGIC],              C, C, _, _, B),
    ArmamentSpec("Coded Sword",                  STRAIGHT_SWORD,       [HOLY],               _, _, _, S, _),
    ArmamentSpec("Sword Of Night And Flame",     STRAIGHT_SWORD,       [MAGIC, FIRE],        C, C, C, C, _),
    ############ GREATSWORDS ############
    ArmamentSpec("Wylder's Greatsword",          GREATSWORD,           [],                   B, C, _, _, _),
    ArmamentSpec("Bastard Sword",                GREATSWORD,           [],                   B, C, _, _, _),
    ArmamentSpec("Iron Greatsword",              GREATSWORD,           [],                   B, C, _, _, _),
    ArmamentSpec("Lordsworn's Greatsword",       GREATSWORD,           [],                   B, C, _, _, _),
    ArmamentSpec("Claymore",                     GREATSWORD,           [],                   B, C, _, _, _),
    ArmamentSpec("Knight's Greatsword",          GREATSWORD,           [],                   B, C, _, _, _),
    ArmamentSpec("Banished Knight's Greatsword", GREATSWORD,           [],                   B, C, _, _, _),
    ArmamentSpec("Forked Greatsword",            GREATSWORD,           [BLEED],              B, C, _, _, _),
    ArmamentSpec("Flamberge",                    GREATSWORD,           [BLEED],              B, C, _, _, _),
    ArmamentSpec("Inseparable Sword",            GREATSWORD,           [HOLY],               B, C, _, C, _),
    ArmamentSpec("Gargoyle's Greatsword",        GREATSWORD,           [],                   B, C, _, _, _),
    ArmamentSpec("Gargoyle's Blackblade",        GREATSWORD,           [HOLY],               B, C, _, C, _),
    ArmamentSpec("Sword Of Milos",               GREATSWORD,           [BLEED],              B, C, _, _, _),
    ArmamentSpec("Ordovis's Greatsword",         GREATSWORD,           [HOLY],               B, C, _, C, _),
    ArmamentSpec("Alabaster Lord's Sword",       GREATSWORD,           [MAGIC],              B, C, C, _, _),
    ArmamentSpec("Death's Poker",                GREATSWORD,           [MAGIC, FROSTBITE],   B, C, C, _, _),
    ArmamentSpec("Helphen's Steeple",            GREATSWORD,           [MAGIC],              B, C, C, _, _),
    ArmamentSpec("Marais Executioner's Sword",   GREATSWORD,           [MAGIC],              B, C, _, _, B),
    ArmamentSpec("Blasphemous Blade",            GREATSWORD,           [FIRE],               B, C, _, C, _),
    ArmamentSpec("Golden Order Greatsword",      GREATSWORD,           [HOLY],               B, C, _, C, _),
    ArmamentSpec("Dark Moon Greatsword",         GREATSWORD,           [MAGIC, FROSTBITE],   B, C, C, _, _),
    ArmamentSpec("Sacred Relic Sword",           GREATSWORD,           [HOLY],               B, C, _, C, _),
    ############ COLLOSAL SWORDS ############
    ArmamentSpec("Zweihander",                   COLOSSAL_SWORD,       [],                   A, C, _, _, _),
    ArmamentSpec("Greatsword",                   COLOSSAL_SWORD,       [],                   A, C, _, _, _),
    ArmamentSpec("Watchdog's Greatsword",        COLOSSAL_SWORD,       [],                   A, C, _, _, _),
    ArmamentSpec("Troll's Golden Sword",         COLOSSAL_SWORD,       [],                   A, C, _, _, _),
    ArmamentSpec("Troll Knight's Sword",         COLOSSAL_SWORD,       [MAGIC],              B, D, D, _, _),
    ArmamentSpec("Royal Greatsword",             COLOSSAL_SWORD,       [MAGIC],              B, D, D, _, _),
    ArmamentSpec("Godslayer's Greatsword",       COLOSSAL_SWORD,       [FIRE],               B, D, _, D, _),
    ArmamentSpec("Grafted Blade Greatsword",     COLOSSAL_SWORD,       [],                   A, C, _, _, _),
    ArmamentSpec("Ruins Greatsword",             COLOSSAL_SWORD,       [MAGIC],              B, D, D, _, _),
    ArmamentSpec("Starscourge Greatsword",       COLOSSAL_SWORD,       [MAGIC],              B, D, D, _, _),
    ArmamentSpec("Maliketh's Black Blade",       COLOSSAL_SWORD,       [HOLY],               B, D, _, D, _),
    ############ THRUSTING SWORDS ############
    ArmamentSpec("Rapier",                       THRUSTING_SWORD,      [],                   E, S, _, _, _),
    ArmamentSpec("Estoc",                        THRUSTING_SWORD,      [],                   E, S, _, _, _),
    ArmamentSpec("Noble's Estoc",                THRUSTING_SWORD,      [],                   E, S, _, _, _),
    ArmamentSpec("Cleanrot Knight's Sword",      THRUSTING_SWORD,      [],                   E, S, _, _, _),
    ArmamentSpec("Rogier's Rapier",              THRUSTING_SWORD,      [],                   E, S, _, _, _),
    ArmamentSpec("Antspur Rapier",               THRUSTING_SWORD,      [SCARLET_ROT],        E, S, _, _, _),
    ArmamentSpec("Frozen Needle",                THRUSTING_SWORD,      [FROSTBITE],          E, S, _, _, _),
    ############ HEAVY THRUSTING SWORDS ############
    ArmamentSpec("Great Épée",                   HEAVY_THRUSTING_SWORD, [],                  C, B, _, _, _),
    ArmamentSpec("Godskin Stitcher",             HEAVY_THRUSTING_SWORD, [],                  C, B, _, _, _),
    ArmamentSpec("Bloody Helice",                HEAVY_THRUSTING_SWORD, [BLEED],             C, B, _, _, C),
    ArmamentSpec("Dragon King's Cragblade",      HEAVY_THRUSTING_SWORD, [],                  C, B, _, _, _),
    ############ CURVED SWORDS ############
    ArmamentSpec("Scimitar",                     CURVED_SWORD,         [],                   D, A, _, _, _),
    ArmamentSpec("Falchion",                     CURVED_SWORD,         [],                   D, A, _, _, _),
    ArmamentSpec("Bandit's Curved Sword",        CURVED_SWORD,         [],                   D, A, _, _, _),
    ArmamentSpec("Shotel",                       CURVED_SWORD,         [],                   D, A, _, _, _),
    ArmamentSpec("Shamshir",                     CURVED_SWORD,         [],                   D, A, _, _, _),
    ArmamentSpec("Grossmesser",                  CURVED_SWORD,         [],                   D, A, _, _, _),
    ArmamentSpec("Scavenger's Curved Sword",     CURVED_SWORD,         [BLEED],              D, A, _, _, _),
    ArmamentSpec("Mantis Blade",                 CURVED_SWORD,         [],                   D, A, _, _, _),
    ArmamentSpec("Beastman's Curved Sword",      CURVED_SWORD,         [],                   D, A, _, _, _),
    ArmamentSpec("Serpent-God's Curved Sword",   CURVED_SWORD,         [],                   D, A, _, _, _),
    ArmamentSpec("Flowing Curved Sword",         CURVED_SWORD,         [],                   D, A, _, _, _),
    ArmamentSpec("Magma Blade",                  CURVED_SWORD,         [FIRE],               D, B, _, D, _),
    ArmamentSpec("Nox Flowing Sword",            CURVED_SWORD,         [],                   D, A, _, _, _),
    ArmamentSpec("Wing Of Astel",                CURVED_SWORD,         [MAGIC],              D, B, D, _, _),
    ArmamentSpec("Eclipse Shotel",               CURVED_SWORD,         [HOLY],               D, B, _, D, _),
    ############ CURVED GREATSWORDS ############
    ArmamentSpec("Dismounter",                   CURVED_GREATSWORD,    [],                   B, B, _, _, _),
    ArmamentSpec("Omen Cleaver",                 CURVED_GREATSWORD,    [],                   B, B, _, _, _),
    ArmamentSpec("Monk's Flameblade",            CURVED_GREATSWORD,    [],                   B, B, _, _, _),
    ArmamentSpec("Beastman's Cleaver",           CURVED_GREATSWORD,    [],                   B, B, _, _, _),
    ArmamentSpec("Bloodhound's Fang",            CURVED_GREATSWORD,    [BLEED],              B, B, _, _, _),
    ArmamentSpec("Onyx Lord's Greatsword",       CURVED_GREATSWORD,    [MAGIC],              C, C, C, _, _),
    ArmamentSpec("Zamor Curved Sword",           CURVED_GREATSWORD,    [FROSTBITE],          B, B, _, _, _),
    ArmamentSpec("Magma Wyrm's Scalesword",      CURVED_GREATSWORD,    [FIRE],               C, C, _, C, _),
    ArmamentSpec("Morgott's Cursed Sword",       CURVED_GREATSWORD,    [BLEED],              C, C, _, _, B),
    ############ KATANAS ############
    ArmamentSpec("Executor's Blade",             KATANA,               [BLEED],              E, S, _, _, _),
    ArmamentSpec("Uchigatana",                   KATANA,               [BLEED],              E, S, _, _, _),
    ArmamentSpec("Nagakiba",                     KATANA,               [BLEED],              E, S, _, _, _),
    ArmamentSpec("Serpentbone Blade",            KATANA,               [POISON],             E, S, _, _, _),
    ArmamentSpec("Meteoric Ore Blade",           KATANA,               [MAGIC, BLEED],       E, A, D, _, _),
    ArmamentSpec("Moonveil",                     KATANA,               [MAGIC, BLEED],       E, A, D, _, _),
    ArmamentSpec("Rivers Of Blood",              KATANA,               [FIRE, BLEED],        E, A, _, _, C),
    ArmamentSpec("Dragonscale Blade",            KATANA,               [],                   E, S, _, _, _),
    ArmamentSpec("Hand Of Malenia",              KATANA,               [BLEED],              E, S, _, _, _),
    ############ TWINBLADES ############
    ArmamentSpec("Twinblade",                    TWINBLADE,            [],                   C, B, _, _, _),
    ArmamentSpec("Twinned Knight Swords",        TWINBLADE,            [],                   C, B, _, _, _),
    ArmamentSpec("Godskin Peeler",               TWINBLADE,            [],                   C, B, _, _, _),
    ArmamentSpec("Gargoyle's Twinblade",         TWINBLADE,            [],                   C, B, _, _, _),
    ArmamentSpec("Gargoyle's Black Blades",      TWINBLADE,            [HOLY],               C, B, _, C, _),
    ArmamentSpec("Eleonora's Poleblade",         TWINBLADE,            [FIRE, BLEED],        C, B, _, _, B),
    ############ AXES ############
    ArmamentSpec("Hand Axe",                     AXE,                  [],                   B, C, _, _, _),
    ArmamentSpec("Forked Hatchet",               AXE,                  [BLEED],              B, C, _, _, _),
    ArmamentSpec("Battle Axe",                   AXE,                  [],                   B, C, _, _, _),
    ArmamentSpec("Jawbone Axe",                  AXE,                  [],                   B, C, _, _, _),
    ArmamentSpec("Warped Axe",                   AXE,                  [],                   B, C, _, _, _),
    ArmamentSpec("Iron Cleaver",                 AXE,                  [],                   B, C, _, _, _),
    ArmamentSpec("Highland Axe",                 AXE,                  [],                   B, C, _, _, _),
    ArmamentSpec("Celebrant's Cleaver",          AXE,                  [],                   B, C, _, _, _),
    ArmamentSpec("Ripple Blade",                 AXE,                  [],                   _, _, _, _, S),
    ArmamentSpec("Icerind Hatchet",              AXE,                  [FROSTBITE],          B, C, _, _, _),
    ArmamentSpec("Sacrificial Axe",              AXE,                  [],                   B, C, _, _, _),
    ArmamentSpec("Stormhawk Axe",                AXE,                  [],                   B, C, _, _, _),
    ArmamentSpec("Rosus' Axe",                   AXE,                  [MAGIC],              C, B, D, _, _),
    ############ GREATAXES ############
    ArmamentSpec("Greataxe",                     GREATAXE,             [],                   S, E, _, _, _),
    ArmamentSpec("Crescent Moon Axe",            GREATAXE,             [],                   S, E, _, _, _),
    ArmamentSpec("Longhaft Axe",                 GREATAXE,             [],                   S, E, _, _, _),
    ArmamentSpec("Executioner's Greataxe",       GREATAXE,             [],                   S, E, _, _, _),
    ArmamentSpec("Great Omenkiller Cleaver",     GREATAXE,             [BLEED],              S, E, _, _, _),
    ArmamentSpec("Rusted Anchor",                GREATAXE,             [],                   S, E, _, _, _),
    ArmamentSpec("Gargoyle's Great Axe",         GREATAXE,             [],                   S, E, _, _, _),
    ArmamentSpec("Gargoyle's Black Axe",         GREATAXE,             [HOLY],               A, E, _, D, _),
    ArmamentSpec("Butchering Knife",             GREATAXE,             [],                   S, E, _, _, _),
    ArmamentSpec("Winged Greathorn",             GREATAXE,             [],                   S, E, _, _, _),
    ArmamentSpec("Axe of Godrick",               GREATAXE,             [],                   S, E, _, _, _),
    ############ HAMMERS ############
    ArmamentSpec("Club",                         HAMMER,               [],                   S, _, _, _, _),
    ArmamentSpec("Curved Club",                  HAMMER,               [],                   A, D, _, _, _),
    ArmamentSpec("Stone Club",                   HAMMER,               [],                   A, D, _, _, _),
    ArmamentSpec("Mace",                         HAMMER,               [],                   A, D, _, _, _),
    ArmamentSpec("Spiked Club",                  HAMMER,               [BLEED],              A, D, _, _, _),
    ArmamentSpec("Morning Star",                 HAMMER,               [BLEED],              A, D, _, _, _),
    ArmamentSpec("Warpick",                      HAMMER,               [],                   A, D, _, _, _),
    ArmamentSpec("Hammer",                       HAMMER,               [],                   A, D, _, _, _),
    ArmamentSpec("Monk's Flamemace",             HAMMER,               [],                   A, D, _, _, _),
    ArmamentSpec("Varré's Bouquet",              HAMMER,               [BLEED],              B, D, _, _, C),
    ArmamentSpec("Envoy's Horn",                 HAMMER,               [HOLY],               B, D, _, D, _),
    ArmamentSpec("Nox Flowing Hammer",           HAMMER,               [],                   A, D, _, _, _),
    ArmamentSpec("Ringed Finger",                HAMMER,               [],                   A, D, _, _, _),
    ArmamentSpec("Scepter Of The All-Knowing",   HAMMER,               [MAGIC],              B, D, D, _, _),
    ArmamentSpec("Marika's Hammer",              HAMMER,               [HOLY],               B, D, _, D, _),
    ############ FLAILS ############
    ArmamentSpec("Flail",                        FLAILS,               [BLEED],              C, B, _, _, _),
    ArmamentSpec("Nightrider Flail",             FLAILS,               [BLEED],              C, B, _, _, _),
    ArmamentSpec("Chainlink Flail",              FLAILS,               [BLEED],              B, C, _, _, _),
    ArmamentSpec("Family Heads",                 FLAILS,               [MAGIC],              C, B, D, _, _),
    ArmamentSpec("Bastard's Stars",              FLAILS,               [MAGIC],              C, B, D, _, _),
    ############ GREAT HAMMERS ############
    ArmamentSpec("Large Club",                   GREAT_HAMMER,         [],                   S, _, _, _, _),
    ArmamentSpec("Curved Great Club",            GREAT_HAMMER,         [],                   S, E, _, _, _),
    ArmamentSpec("Great Mace",                   GREAT_HAMMER,         [],                   S, E, _, _, _),
    ArmamentSpec("Pickaxe",                      GREAT_HAMMER,         [],                   S, E, _, _, _),
    ArmamentSpec("Brick Hammer",                 GREAT_HAMMER,         [],                   S, E, _, _, _),
    ArmamentSpec("Battle Hammer",                GREAT_HAMMER,         [],                   S, E, _, _, _),
    ArmamentSpec("Rotten Battle Hammer",         GREAT_HAMMER,         [SCARLET_ROT],        S, E, _, _, _),
    ArmamentSpec("Celebrant's Skull",            GREAT_HAMMER,         [],                   S, E, _, _, _),
    ArmamentSpec("Great Stars",                  GREAT_HAMMER,         [BLEED],              S, E, _, _, _),
    ArmamentSpec("Greathorn Hammer",             GREAT_HAMMER,         [],                   S, E, _, _, _),
    ArmamentSpec("Envoy's Long Horn",            GREAT_HAMMER,         [HOLY],               A, E, _, D, _),
    ArmamentSpec("Cranial Vessel Candlestand",   GREAT_HAMMER,         [FIRE],               A, E, _, D, _),
    ArmamentSpec("Beastclaw Greathammer",        GREAT_HAMMER,         [HOLY],               A, E, _, D, _),
    ArmamentSpec("Devourer's Scepter",           GREAT_HAMMER,         [FIRE],               A, E, _, D, _),
    ############ COLOSSAL WEAPONS ############
    ArmamentSpec("Raider's Greataxe",            COLOSSAL_WEAPON,      [],                   S, _, _, _, _),
    ArmamentSpec("Duelist Greataxe",             COLOSSAL_WEAPON,      [],                   S, _, _, _, _),
    ArmamentSpec("Rotten Greataxe",              COLOSSAL_WEAPON,      [SCARLET_ROT],        S, _, _, _, _),
    ArmamentSpec("Golem's Halberd",              COLOSSAL_WEAPON,      [],                   S, _, _, _, _),
    ArmamentSpec("Giant-Crusher",                COLOSSAL_WEAPON,      [],                   S, _, _, _, _),
    ArmamentSpec("Great Club",                   COLOSSAL_WEAPON,      [HOLY],               A, _, _, D, _),
    ArmamentSpec("Troll's Hammer",               COLOSSAL_WEAPON,      [FIRE],               A, _, _, D, _),
    ArmamentSpec("Prelate's Inferno Crozier",    COLOSSAL_WEAPON,      [],                   S, _, _, _, _),
    ArmamentSpec("Dragon Greatclaw",             COLOSSAL_WEAPON,      [LIGHTNING],          S, _, _, _, _),
    ArmamentSpec("Watchdog's Staff",             COLOSSAL_WEAPON,      [],                   S, _, _, _, _),
    ArmamentSpec("Staff Of The Avatar",          COLOSSAL_WEAPON,      [HOLY],               A, _, _, D, _),
    ArmamentSpec("Rotten Staff",                 COLOSSAL_WEAPON,      [SCARLET_ROT],        S, _, _, _, _),
    ArmamentSpec("Envoy's Greathorn",            COLOSSAL_WEAPON,      [HOLY],               A, _, _, D, _),
    ArmamentSpec("Ghiza's Wheel",                COLOSSAL_WEAPON,      [BLEED],              S, _, _, _, _),
    ArmamentSpec("Fallingstar Beast Jaw",        COLOSSAL_WEAPON,      [MAGIC],              A, _, D, _, _),
    ArmamentSpec("Axe Of Godfrey",               COLOSSAL_WEAPON,      [],                   S, _, _, _, _),
    ############ SPEARS ############
    ArmamentSpec("Short Spear",                  SPEAR,                [],                   C, B, _, _, _),
    ArmamentSpec("Iron Spear",                   SPEAR,                [],                   C, B, _, _, _),
    ArmamentSpec("Spear",                        SPEAR,                [],                   C, B, _, _, _),
    ArmamentSpec("Partisan",                     SPEAR,                [],                   C, B, _, _, _),
    ArmamentSpec("Pike",                         SPEAR,                [],                   C, B, _, _, _),
    ArmamentSpec("Spiked Spear",                 SPEAR,                [BLEED],              C, B, _, _, _),
    ArmamentSpec("Cross-Naginata",               SPEAR,                [BLEED],              C, B, _, _, _),
    ArmamentSpec("Clayman's Harpoon",            SPEAR,                [MAGIC],              C, B, C, _, _),
    ArmamentSpec("Celebrant's Rib-Rake",         SPEAR,                [],                   C, B, _, _, _),
    ArmamentSpec("Torchpole",                    SPEAR,                [FIRE],               C, B, _, _, _),
    ArmamentSpec("Crystal Spear",                SPEAR,                [MAGIC],              C, B, C, _, _),
    ArmamentSpec("Rotten Crystal Spear",         SPEAR,                [MAGIC, SCARLET_ROT], C, B, C, _, _),
    ArmamentSpec("Inquisitor's Girandole",       SPEAR,                [FIRE, BLEED],        C, B, _, C, _),
    ArmamentSpec("Cleanrot Spear",               SPEAR,                [HOLY],               C, B, _, C, _),
    ArmamentSpec("Death Ritual Spear",           SPEAR,                [MAGIC],              C, B, C, _, _),
    ArmamentSpec("Bolt Of Gransax",              SPEAR,                [LIGHTNING],          C, B, _, _, _),
    ############ GREAT SPEARS ############
    ArmamentSpec("Lance",                        GREAT_SPEAR,          [],                   B, C, _, _, _),
    ArmamentSpec("Treespear",                    GREAT_SPEAR,          [HOLY],               C, B, _, D, _),
    ArmamentSpec("Serpent-Hunter",               GREAT_SPEAR,          [],                   B, C, _, _, _),
    ArmamentSpec("Siluria's Tree",               GREAT_SPEAR,          [HOLY],               B, C, _, D, _),
    ArmamentSpec("Vyke's War Spear",             GREAT_SPEAR,          [FIRE, MADNESS],      B, C, _, D, _),
    ArmamentSpec("Mohgwyn's Sacred Spear",       GREAT_SPEAR,          [FIRE, BLEED],        B, C, _, _, C),
    ############ HALBERDS ############
    ArmamentSpec("Guardian's Halberd",           HALBERD,              [],                   B, C, _, _, _),
    ArmamentSpec("Halberd",                      HALBERD,              [],                   B, C, _, _, _),
    ArmamentSpec("Banished Knight's Halberd",    HALBERD,              [],                   B, C, _, _, _),
    ArmamentSpec("Lucerne",                      HALBERD,              [],                   B, C, _, _, _),
    ArmamentSpec("Glaive",                       HALBERD,              [],                   B, C, _, _, _),
    ArmamentSpec("Vulgar Militia Shotel",        HALBERD,              [],                   B, C, _, _, _),
    ArmamentSpec("Vulgar Militia Saw",           HALBERD,              [BLEED],              B, C, _, _, _),
    ArmamentSpec("Guardian's Swordspear",        HALBERD,              [],                   E, S, _, _, _),
    ArmamentSpec("Nightrider Glaive",            HALBERD,              [],                   B, C, _, _, _),
    ArmamentSpec("Pest's Glaive",                HALBERD,              [],                   B, C, _, _, _),
    ArmamentSpec("Ripple Crescent Halberd",      HALBERD,              [],                   _, _, _, _, S),
    ArmamentSpec("Gargoyle's Halberd",           HALBERD,              [],                   B, C, _, _, _),
    ArmamentSpec("Gargoyle's Black Halberd",     HALBERD,              [HOLY],               B, C, _, C, _),
    ArmamentSpec("Golden Halberd",               HALBERD,              [HOLY],               B, C, _, C, _),
    ArmamentSpec("Dragon Halberd",               HALBERD,              [],                   B, C, _, _, _),
    ArmamentSpec("Loretta's War Sickle",         HALBERD,              [MAGIC],              B, C, C, _, _),
    ArmamentSpec("Commander's Standard",         HALBERD,              [],                   B, C, _, _, _),
    ############ REAPERS ############
    ArmamentSpec("Scythe",                       REAPER,               [BLEED],              D, A, _, _, _),
    ArmamentSpec("Grave Scythe",                 REAPER,               [BLEED],              D, A, _, _, _),
    ArmamentSpec("Halo Scythe",                  REAPER,               [HOLY, BLEED],        D, B, _, D, _),
    ArmamentSpec("Winged Scythe",                REAPER,               [HOLY, BLEED],        D, B, _, D, _),
    ############ WHIPS ############
    ArmamentSpec("Whip",                         WHIP,                 [],                   D, A, _, _, _),
    ArmamentSpec("Thorned Whip",                 WHIP,                 [BLEED],              D, A, _, _, _),
    ArmamentSpec("Urumi",                        WHIP,                 [],                   D, A, _, _, _),
    ArmamentSpec("Hoslow's Petal Whip",          WHIP,                 [BLEED],              D, A, _, _, _),
    ArmamentSpec("Magma Whip Candlestick",       WHIP,                 [FIRE],               D, A, _, D, _),
    ArmamentSpec("Giant's Red Braid",            WHIP,                 [FIRE],               D, A, _, D, _),
    ############ FISTS ############
    ArmamentSpec("Revenant's Cursed Claws",      FIST,                 [MAGIC],              E, _, _, S, _),
    ArmamentSpec("Katar",                        FIST,                 [],                   B, C, _, _, _),
    ArmamentSpec("Caestus",                      FIST,                 [],                   B, C, _, _, _),
    ArmamentSpec("Spiked Caestus",               FIST,                 [BLEED],              B, C, _, _, _),
    ArmamentSpec("Iron Ball",                    FIST,                 [],                   B, C, _, _, _),
    ArmamentSpec("Star Fist",                    FIST,                 [BLEED],              B, C, _, _, _),
    ArmamentSpec("Clinging Bone",                FIST,                 [MAGIC],              B, C, _, _, B),
    ArmamentSpec("Veteran's Prosthesis",         FIST,                 [LIGHTNING],          B, C, _, _, _),
    ArmamentSpec("Cipher Pata",                  FIST,                 [HOLY],               _, _, _, S, _),
    ArmamentSpec("Grafted Dragon",               FIST,                 [FIRE],               B, C, _, C, _),
    ############ CLAWS ############
    ArmamentSpec("Hookclaws",                    CLAWS,                [BLEED],              D, A, _, _, _),
    ArmamentSpec("Bloodhound Claws",             CLAWS,                [BLEED],              D, A, _, _, _),
    ArmamentSpec("Venomous Fang",                CLAWS,                [POISON],             D, A, _, _, _),
    ArmamentSpec("Raptor Talons",                CLAWS,                [BLEED],              D, A, _, _, _),
    ############ BOWS ############
    ArmamentSpec("Ironeye's Bow",                BOW,                  [],                   E, S, _, _, _),
    ArmamentSpec("Shortbow",                     BOW,                  [],                   E, S, _, _, _),
    ArmamentSpec("Misbegotten Shortbow",         BOW,                  [],                   E, S, _, _, _),
    ArmamentSpec("Longbow",                      BOW,                  [],                   E, S, _, _, _),
    ArmamentSpec("Composite Bow",                BOW,                  [],                   E, S, _, _, _),
    ArmamentSpec("Red Branch Shortbow",          BOW,                  [],                   E, S, _, _, _),
    ArmamentSpec("Harp Bow",                     BOW,                  [],                   E, S, _, _, _),
    ArmamentSpec("Albinauric Bow",               BOW,                  [],                   E, S, _, _, _),
    ArmamentSpec("Horn Bow",                     BOW,                  [MAGIC],              E, A, D, _, _),
    ArmamentSpec("Black Bow",                    BOW,                  [],                   E, S, _, _, _),
    ArmamentSpec("Pulley Bow",                   BOW,                  [],                   E, S, _, _, _),
    ArmamentSpec("Serpent Bow",                  BOW,                  [POISON],             E, A, _, _, C),
    ArmamentSpec("Erdtree Bow",                  BOW,                  [HOLY],               E, A, _, D, _),
    ############ GREATBOWS ############
    ArmamentSpec("Greatbow",                     GREATBOW,             [],                   B, C, _, _, _),
    ArmamentSpec("Golem Greatbow",               GREATBOW,             [],                   B, C, _, _, _),
    ArmamentSpec("Erdtree Greatbow",             GREATBOW,             [HOLY],               C, C, _, C, _),
    ArmamentSpec("Lion Greatbow",                GREATBOW,             [],                   B, C, _, _, _),
    ############ CROSSBOWS ############
    ArmamentSpec("Soldier's Crossbow",           CROSSBOW,             [],                   _, _, _, _, _),
    ArmamentSpec("Light Crossbow",               CROSSBOW,             [],                   _, _, _, _, _),
    ArmamentSpec("Heavy Crossbow",               CROSSBOW,             [],                   _, _, _, _, _),
    ArmamentSpec("Arbalest",                     CROSSBOW,             [],                   _, _, _, _, _),
    ArmamentSpec("Crepus's Black-Key Crossbow",  CROSSBOW,             [],                   _, _, _, _, _),
    ArmamentSpec("Full Moon Crossbow",           CROSSBOW,             [MAGIC],              _, _, _, _, _),
    ArmamentSpec("Pulley Crossbow",              CROSSBOW,             [],                   _, _, _, _, _),
    ############ BALLISTAS ############
    ArmamentSpec("Hand Ballista",                BALLISTA,             [],                   _, _, _, _, _),
    ArmamentSpec("Jar Cannon",                   BALLISTA,             [],                   _, _, _, _, _),
    ############ TORCHES ############
    ArmamentSpec("Torch",                        TORCH,                [FIRE],               B, B, _, _, _),
    ArmamentSpec("Beast-Repellent Torch",        TORCH,                [FIRE],               B, B, _, _, _),
    ArmamentSpec("Steel-Wire Torch",             TORCH,                [FIRE],               B, B, _, _, _),
    ArmamentSpec("Sentry's Torch",               TORCH,                [FIRE, HOLY],         C, C, _, D, _),
    ArmamentSpec("Ghostflame Torch",             TORCH,                [MAGIC, FROSTBITE],   C, C, D, _, _),
    ArmamentSpec("St. Trina's Torch",            TORCH,                [FIRE, SLEEP],        C, C, _, D, _),
    ############ SMALL SHIELDS ############
    ArmamentSpec("Wylder's Small Shield",        SMALL_SHIELD,         [],                   B, C, _, _, _),
    ArmamentSpec("Rickety Shield",               SMALL_SHIELD,         [],                   B, C, _, _, _),
    ArmamentSpec("Riveted Wooden Shield",        SMALL_SHIELD,         [],                   B, C, _, _, _),
    ArmamentSpec("Blue-White Wooden Shield",     SMALL_SHIELD,         [],                   B, C, _, _, _),
    ArmamentSpec("Scripture Wooden Shield",      SMALL_SHIELD,         [],                   B, C, _, _, _),
    ArmamentSpec("Red Thorn Roundshield",        SMALL_SHIELD,         [],                   B, C, _, _, _),
    ArmamentSpec("Pillory Shield",               SMALL_SHIELD,         [],                   B, C, _, _, _),
    ArmamentSpec("Buckler",                      SMALL_SHIELD,         [],                   B, C, _, _, _),
    ArmamentSpec("Iron Roundshield",             SMALL_SHIELD,         [],                   B, C, _, _, _),
    ArmamentSpec("Gilded Iron Shield",           SMALL_SHIELD,         [],                   B, C, _, _, _),
    ArmamentSpec("Man-Serpent's Shield",         SMALL_SHIELD,         [],                   B, C, _, _, _),
    ArmamentSpec("Ice Crest Shield",             SMALL_SHIELD,         [],                   B, C, _, _, _),
    ArmamentSpec("Rift Shield",                  SMALL_SHIELD,         [],                   B, C, _, _, _),
    ArmamentSpec("Perfumer's Shield",            SMALL_SHIELD,         [],                   B, C, _, _, _),
    ArmamentSpec("Shield Of The Guilty",         SMALL_SHIELD,         [BLEED],              B, C, _, _, _),
    ArmamentSpec("Spiralhorn Shield",            SMALL_SHIELD,         [BLEED],              B, C, _, _, _),
    ArmamentSpec("Smoldering Shield",            SMALL_SHIELD,         [FIRE],               B, C, _, D, _),
    ArmamentSpec("Coil Shield",                  SMALL_SHIELD,         [POISON],             B, C, _, _, _),
    ############ MEDIUM SHIELDS ############
    ArmamentSpec("Hawk Crest Wooden Shield",     MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Horse Crest Wooden Shield",    MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Candletree Wooden Shield",     MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Flame Crest Wooden Shield",    MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Marred Wooden Shield",         MEDIUM_SHIELD,        [BLEED],              A, D, _, _, _),
    ArmamentSpec("Round Shield",                 MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Marred Leather Shield",        MEDIUM_SHIELD,        [BLEED],              A, D, _, _, _),
    ArmamentSpec("Heater Shield",                MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Blue Crest Heater Shield",     MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Red Crest Heater Shield",      MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Beast Crest Heater Shield",    MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Inverted Hawk Heater Shield",  MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Eclipse Crest Heater Shield",  MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Sun Realm Shield",             MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Large Leather Shield",         MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Black Leather Shield",         MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Kite Shield",                  MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Blue-Gold Kite Shield",        MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Scorpion Kite Shield",         MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Twinbird Kite Shield",         MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Brass Shield",                 MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Banished Knight's Shield",     MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Albinauric Shield",            MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Beastman's Jar-Shield",        MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ArmamentSpec("Carian Knight's Shield",       MEDIUM_SHIELD,        [MAGIC],              B, D, D, _, _),
    ArmamentSpec("Silver Mirrorshield",          MEDIUM_SHIELD,        [MAGIC],              B, D, D, _, _),
    ArmamentSpec("Great Turtle Shell",           MEDIUM_SHIELD,        [],                   A, D, _, _, _),
    ############ GREATSHIELDS ############
    ArmamentSpec("Guardian's Greatshield",       GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Wooden Greatshield",           GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Lordsworn's Shield",           GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Manor Towershield",            GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Crossed-Tree Towershield",     GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Inverted Hawk Towershield",    GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Dragon Towershield",           GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Briar Greatshield",            GREATSHIELD,          [BLEED],              A, D, _, _, _),
    ArmamentSpec("Spiked Palisade Shield",       GREATSHIELD,          [BLEED],              A, D, _, _, _),
    ArmamentSpec("Icon Shield",                  GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Golden Beast Crest Shield",    GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Distinguished Greatshield",    GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Gilded Greatshield",           GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Cuckoo Greatshield",           GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Redmane Greatshield",          GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Golden Greatshield",           GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Haligtree Crest Greatshield",  GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Eclipse Crest Greatshield",    GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Crucible Hornshield",          GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Dragonclaw Shield",            GREATSHIELD,          [LIGHTNING],          A, D, _, _, _),
    ArmamentSpec("Fingerprint Stone Shield",     GREATSHIELD,          [MADNESS],            A, D, _, _, _),
    ArmamentSpec("Ant's Skull Plate",            GREATSHIELD,          [POISON],             A, D, _, _, _),
    ArmamentSpec("Erdtree Greatshield",          GREATSHIELD,          [HOLY],               A, D, _, D, _),
    ArmamentSpec("Jellyfish Shield",             GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("Visage Shield",                GREATSHIELD,          [],                   A, D, _, _, _),
    ArmamentSpec("One-Eyed Shield",              GREATSHIELD,          [],                   A, D, _, _, _),
    ############ GLINTSTONE STAFFS ############
    ArmamentSpec("Recluse's Staff",              GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Astrologer's Staff",           GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Glintstone Staff",             GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Academy Glintstone Staff",     GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Digger's Staff",               GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Demi-Human Queen's Staff",     GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Carian Glintstone Staff",      GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Carian Glintblade Staff",      GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Albinauric Staff",             GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Staff Of Loss",                GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Gelmir Glintstone Staff",      GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Crystal Staff",                GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Rotten Crystal Staff",         GLINTSTONE_STAFF,     [SCARLET_ROT],        _, _, S, _, _),
    ArmamentSpec("Staff Of The Guilty",          GLINTSTONE_STAFF,     [BLEED],              _, _, S, _, _),
    ArmamentSpec("Azur's Glintstone Staff",      GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Lusat's Glintstone Staff",     GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Meteorite Staff",              GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Prince Of Death's Staff",      GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ArmamentSpec("Carian Regal Scepter",         GLINTSTONE_STAFF,     [],                   _, _, S, _, _),
    ############ SACRED SEALS ############
    ArmamentSpec("Finger Seal",                  SACRED_SEAL,          [],                   _, _, _, S, _),
    ArmamentSpec("Gravel Stone Seal",            SACRED_SEAL,          [],                   _, _, _, S, _),
    ArmamentSpec("Giant's Seal",                 SACRED_SEAL,          [],                   _, _, _, S, _),
    ArmamentSpec("Godslayer's Seal",             SACRED_SEAL,          [],                   _, _, _, S, _),
    ArmamentSpec("Clawmark Seal",                SACRED_SEAL,          [],                   _, _, _, S, _),
    ArmamentSpec("Erdtree Seal",                 SACRED_SEAL,          [HOLY],               _, _, _, S, _),
    ArmamentSpec("Golden Order Seal",            SACRED_SEAL,          [],                   _, _, _, S, _),
    ArmamentSpec("Frenzied Flame Seal",          SACRED_SEAL,          [MADNESS],            _, _, _, S, _),
    ArmamentSpec("Dragon Communion Seal",        SACRED_SEAL,          [],                   _, _, _, S, _),
])